services:
  catalog-collector:
    build:
      context: catalog-collector
      dockerfile: Dockerfile
    env_file:
      - catalog-collector/.env.development
  catalog-ingester:
    build:
      context: catalog-ingester
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - text-embeddings-inference
    env_file:
      - catalog-ingester/.env.development
  text-embeddings-inference:
    ports:
      - "${TEXT_EMBEDDINGS_PORT:-38080}:80"
    volumes:
      - hf_cache:/data
    pull_policy: always
    restart: unless-stopped
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.9.1
    command: >
      --model-id intfloat/multilingual-e5-small
      --pooling mean 
      --max-batch-tokens 16384 
      --max-client-batch-size 8
      --auto-truncate
volumes:
  hf_cache:
    external: true
    name: hf_cache
