services:
  catalog-collector:
    image: mateuszkurowski/catalog-collector:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_LOGS_EXPORTER=otlp
      - DATASET_OUTPUT_DIR=dataset
      - OTEL_EXPORTER_OTLP_INSECURE=false
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_SERVICE_NAME=catalog-collector
      - DEBUG=false

  text-embeddings-inference:
    ports:
      - 8080:80
    volumes:
      - hf_cache:/data
    pull_policy: always
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.9.1
    command:
      --model-id Qwen/Qwen3-Embedding-0.6B --revision refs/pr/27 --pooling
      mean --max-batch-tokens 2048 --max-client-batch-size 16
      --auto-truncate
volumes:
  hf_cache:
    external: true
    name: hf_cache
