services:
  catalog-collector:
    container_name: catalog-collector
    build:
      context: ./catalog-collector
      dockerfile: Dockerfile
    restart: on-failure
    pull_policy: never
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=${DEBUG:-false}
      - PRODUCTION=${PRODUCTION:-false}
      - CATALOG_COLLECTOR_SERVICE_ON=${CATALOG_COLLECTOR_SERVICE_ON:-true}
      - DATASET_LOAD_PERCENTAGE=${DATASET_LOAD_PERCENTAGE:-100}

  catalog-ingester:
    container_name: catalog-ingester
    build:
      context: ./catalog-ingester
      dockerfile: Dockerfile
    restart: unless-stopped
    pull_policy: never
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=${DEBUG:-false}
      - PRODUCTION=${PRODUCTION:-false}
      - INGEST_BATCH_SIZE=${INGEST_BATCH_SIZE:-8}
      - INGEST_PERIOD_SECONDS=${INGEST_PERIOD_SECONDS:-15}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT:-6334}
      - QDRANT_USE_SSL=${QDRANT_USE_SSL:-false}
      - QDRANT_COLLECTION_NAME=${QDRANT_COLLECTION_NAME:-movies}
      - QDRANT_DENSE_VECTOR_NAME=${QDRANT_DENSE_VECTOR_NAME:-overview-dense-vector}
      - QDRANT_SPARSE_VECTOR_NAME=${QDRANT_SPARSE_VECTOR_NAME:-overview-sparse-vector}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDING_TIMEOUT_SECONDS=${EMBEDDING_TIMEOUT_SECONDS:-30}
      - EMBEDDING_MAX_PARALLEL=${EMBEDDING_MAX_PARALLEL:-2}
      - CHUNK_SIZE=${CHUNK_SIZE:-1200}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-120}
      - VECTOR_DIMENSION=${VECTOR_DIMENSION:-256}

  catalog-api:
    container_name: catalog-api
    build:
      context: ./catalog-api
      dockerfile: Dockerfile
    restart: unless-stopped
    pull_policy: never
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=${DEBUG:-false}
      - PRODUCTION=${PRODUCTION:-false}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${SEARCH_API_QDRANT_PORT:-6333}
      - QDRANT_SSL=${QDRANT_SSL:-false}
      - QDRANT_COLLECTION_NAME=${QDRANT_COLLECTION_NAME:-movies}
      - QDRANT_DENSE_VECTOR_NAME=${QDRANT_DENSE_VECTOR_NAME:-overview-dense-vector}
      - QDRANT_SPARSE_VECTOR_NAME=${QDRANT_SPARSE_VECTOR_NAME:-overview-sparse-vector}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL:-voyage/voyage-4-lite}
      - OPENAI_EMBEDDING_MODEL_DIMENSION=${OPENAI_EMBEDDING_MODEL_DIMENSION:-256}
      - REDIS_URL=${REDIS_URL}
