services:
  catalog-collector:
    build:
      context: catalog-collector
      dockerfile: Dockerfile
    restart: on-failure
    pull_policy: always
    environment:
      - CATALOG_COLLECTOR_SERVICE_ON=${CATALOG_COLLECTOR_SERVICE_ON}
      - DATABASE_URL=${DATABASE_URL}
      - DATASET_OUTPUT_DIR=dataset
      - DATASET_LOAD_PERCENTAGE=${DATASET_LOAD_PERCENTAGE:-100}
      - DEBUG=false
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_INSECURE=false
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=production
      - OTEL_SERVICE_NAME=catalog-collector
  catalog-ingester:
    build:
      context: catalog-ingester
      dockerfile: Dockerfile
    restart: unless-stopped
    pull_policy: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=${DEBUG}
      - INGEST_BATCH_SIZE=8
      - INGEST_PERIOD_SECONDS=${INGEST_PERIOD_SECONDS}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_INSECURE=false
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=production
      - OTEL_SERVICE_NAME=catalog-ingester
      - PRODUCTION=true
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_COLLECTION_NAME=${QDRANT_COLLECTION_NAME}
      - QDRANT_DENSE_VECTOR_NAME=${QDRANT_DENSE_VECTOR_NAME}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_INFERENCE_MODEL=${QDRANT_INFERENCE_MODEL}
      - QDRANT_PORT=${QDRANT_PORT}
      - USE_QDRANT_INFERENCE=${USE_QDRANT_INFERENCE}
  text-embeddings-inference:
    ports:
      - "${TEXT_EMBEDDINGS_PORT:-38080}:80"
    volumes:
      - hf_cache:/data
    pull_policy: always
    restart: unless-stopped
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.9.1
    command: >
      --model-id intfloat/multilingual-e5-small
      --pooling mean 
      --max-batch-tokens 16384 
      --max-client-batch-size 8
      --auto-truncate
volumes:
  hf_cache:
    external: true
    name: hf_cache
