sonar.projectKey=Semantic-Movie-Show-Discovery-App

sonar.projectName=Semantic-Movie-Show-Discovery-App

sonar.sources=catalog-collector/src,catalog-ingester

sonar.tests=catalog-ingester
sonar.test.inclusions=**/*_test.go

sonar.exclusions=**/vendor/**,**/.venv/**,**/dataset/**,**/node_modules/**,**/*.lock,**/cover.out,**/*_test.go

sonar.go.coverage.reportPaths=catalog-ingester/cover.out

sonar.sourceEncoding=UTF-8
