pre-commit:
  parallel: true
  commands:
    golangci-lint:
      glob: "*.{go,mod,sum}"
      root: catalog-ingester
      run: golangci-lint run --fix
      stage_fixed: true
    go-fmt:
      glob: "*.go"
      root: catalog-ingester
      run: go fmt ./...
      stage_fixed: true
