pre-commit:
  parallel: true
  commands:
    golangci-lint:
      glob: "*.{go,mod,sum}"
      run: golangci-lint run --fix
      stage_fixed: true
    go-fmt:
      glob: "*.go"
      run: go fmt {staged_files}
      stage_fixed: true
